environment:
  - "FORCE_COLOR=1"
processes:

  yarn-install:
    command: yarn --cwd ./frontend install --color=always

  vite-dev:
    command: yarn --cwd ./frontend dev --host 0.0.0.0 --port 12345 --strictPort
    ports:
      - 5173:5173
    depends_on:
      yarn-install:
        condition: process_completed_successfully

  # uvicorn-dev:
  #   command: uvicorn --port 5179 --app-dir ./backend main:app --reload
  #   ports:
  #     - 5173:5173
