import { HashSet } from "effect"
import { TagFilter, TagFilterSimple } from "../models/TagFilter"

export const technologies = HashSet.fromIterable([
    TagFilterSimple("React"),
    TagFilterSimple("Python"),
    TagFilterSimple("Typescript"),
    TagFilterSimple("NodeJS"),
    TagFilterSimple("JavaScript"),
    TagFilterSimple("Go"),
    TagFilterSimple("Ruby"),
    TagFilterSimple("Kubernetes"),
    TagFilterSimple("Java"),
    TagFilterSimple("Ruby on Rails"),
    TagFilterSimple("iOS"),
    TagFilterSimple("Android"),
    TagFilter({name: "C++", pattern: RegExp(/(^|\b|\s)(C\+\+[0-9]{0,2})($|\W|\s)/, "gmi")}),
    TagFilterSimple("React Native"),
    TagFilterSimple("Rust"),
    TagFilterSimple("Angular"),
    TagFilterSimple("VueJS"),
    TagFilterSimple("PHP"),
    TagFilterSimple(".NET"),
    TagFilterSimple("C#"),
    TagFilterSimple("Kotlin"),
    TagFilter({name: "Scala", pattern: RegExp(/(^|\b|\s)(Scala[0-9]{0,1})($|\b|\s)/, "gmi")}),
    TagFilterSimple("Kafka"),
    TagFilterSimple("Swift"),
    TagFilterSimple("Elixir"),
    TagFilter({name: "C", pattern: RegExp(/(^|\b|\s)(C)($|\b|\s|^\+|^#)/, "gm")}),
    TagFilterSimple("Next.js"),
    TagFilterSimple("Clojure"),
    TagFilterSimple("Tensorflow"),
    TagFilterSimple("Haskell"),
    TagFilterSimple("EmberJS"),
    TagFilterSimple("Dart"),
    TagFilterSimple("Flutter"),
    TagFilterSimple("Snowflake"),
    TagFilterSimple("WebAssembly"),
    TagFilterSimple("Julia"),
    TagFilterSimple("Elm"),
    TagFilterSimple("Perl"),
    TagFilterSimple("Clickhouse"),
    TagFilterSimple("Ocaml"),
    TagFilterSimple("Svelte"),
    TagFilterSimple("Lua"),
    TagFilterSimple("AWS"),
    TagFilterSimple("Firebase"),
])

export const locations = HashSet.fromIterable([
    TagFilterSimple("Remote"),
    TagFilter({name: "San Francisco / SF", pattern: RegExp(/(^|\b|\s)(San Francisco|SF)($|\b|\s)/, "gmi")}),
    TagFilterSimple("New York City"),
    TagFilterSimple("London"),
    TagFilterSimple("Boston"),
    TagFilterSimple("Berlin"),
    TagFilterSimple("Los Angeles"),
    TagFilterSimple("Seattle"),
    TagFilterSimple("Austin"),
    TagFilterSimple("Toronto"),
    TagFilterSimple("Amsterdam"),
    TagFilterSimple("Chicago"),
    TagFilterSimple("DC"),
    TagFilterSimple("Paris"),
    TagFilterSimple("Palo Alto"),
    TagFilterSimple("Cambridge (MA)"),
    TagFilterSimple("Munich"),
    TagFilterSimple("Vancouver"),
    TagFilterSimple("Denver"),
    TagFilterSimple("Singapore"),
    TagFilterSimple("Atlanta"),
    TagFilterSimple("San Diego"),
    TagFilterSimple("Bangalore"),
    TagFilterSimple("Montreal"),
    TagFilterSimple("Mountain View"),
    TagFilterSimple("Philadelphia"),
    TagFilterSimple("Boulder"),
    TagFilterSimple("San Mateo"),
    TagFilterSimple("Portland"),
    TagFilterSimple("Sydney"),
    TagFilterSimple("Berkeley"),
    TagFilterSimple("Tokyo"),
    TagFilterSimple("Oakland"),
    TagFilterSimple("Zurich"),
    TagFilterSimple("Barcelona"),
    TagFilterSimple("Brooklyn"),
    TagFilterSimple("Dublin"),
    TagFilterSimple("Pittsburgh"),
    TagFilterSimple("Redwood City"),
    TagFilterSimple("Oslo"),
    TagFilterSimple("Hong Kong"),
    TagFilterSimple("Lisbon"),
    TagFilterSimple("Dallas"),
    TagFilterSimple("San Jose"),
    TagFilterSimple("Edinburgh"),
    TagFilterSimple("Budapest"),
    TagFilterSimple("Sunnyvale"),
    TagFilterSimple("Menlo Park"),
    TagFilterSimple("Salt Lake City"),
    TagFilterSimple("Houston"),
    TagFilterSimple("Warsaw"),
    TagFilterSimple("Cambridge (UK)"),
    TagFilterSimple("Melbourne (FL)"),
    TagFilterSimple("Melbourne (AU)"),
    TagFilterSimple("Ann Arbor"),
    TagFilterSimple("Madrid"),
    TagFilterSimple("Durham"),
    TagFilterSimple("Oxford"),
    TagFilterSimple("Prague"),
    TagFilterSimple("Charlotte"),
    TagFilterSimple("Raleigh"),
    TagFilterSimple("Pune"),
    TagFilterSimple("Detroit"),
    TagFilterSimple("Princeton"),
    TagFilterSimple("Irvine"),
    TagFilterSimple("Cologne"),
    TagFilterSimple("Bangkok"),
    TagFilterSimple("Cupertino"),
    TagFilterSimple("Shanghai"),
    TagFilterSimple("Shenzhen"),
    TagFilterSimple("Ghent"),
    TagFilterSimple("Hyderabad"),
    TagFilterSimple("Dubai"),
    TagFilterSimple("Eindhoven"),
    TagFilterSimple("Chennai"),
    TagFilterSimple("Lausanne"),
    TagFilterSimple("Burlingame"),
    TagFilterSimple("Sao Paulo"),
    TagFilterSimple("Beijing"),
    TagFilterSimple("Seoul"),
    TagFilterSimple("Auckland"),
    TagFilterSimple("Tampa"),
    TagFilterSimple("Mexico City"),
    TagFilterSimple("Emeryville"),
    TagFilterSimple("Phoenix (AZ)"),
    TagFilterSimple("Cape Town"),
    TagFilterSimple("Kansas City"),
    TagFilterSimple("Leuven"),
    TagFilterSimple("Brussels"),
    TagFilterSimple("Trondheim"),
    TagFilterSimple("Guadalajara"),
    TagFilterSimple("Lincoln"),
    TagFilterSimple("Wellington"),
    TagFilterSimple("Tucson"),
    TagFilterSimple("Manila"),
    TagFilterSimple("Los Gatos"),
    TagFilterSimple("Antwerp"),
    TagFilterSimple("Bogotá"),
    TagFilterSimple("San Ramon"),
    TagFilterSimple("Knoxville"),
    TagFilterSimple("Hangzhou"),
    TagFilterSimple("Bratislava"),
    TagFilterSimple("Braga"),
    TagFilterSimple("Geneve"),
])

export const role = HashSet.fromIterable([
    TagFilter({name: "Developer / Engineer", pattern: RegExp(/(^|\b|\s)(Developer|Engineer)($|\b|\s)/, "gmi")}),
    TagFilterSimple("Developer"),
    TagFilterSimple("Product Manager"),
    TagFilterSimple("Data Scientist"),
    TagFilterSimple("Machine Learning"),
    TagFilterSimple("AI Engineer"),
    TagFilterSimple("Software Engineer"),
    TagFilterSimple("Founding Engineer"),
    TagFilterSimple("Infrastructure Engineer"),
    TagFilterSimple("Manager"),
    TagFilterSimple("Lead"),
    TagFilterSimple("Staff"),
    TagFilter({name: "Senior / Sr", pattern: RegExp(/(^|\b|\s)(Senior|Sr)($|\b|\s)/, "gmi")}),
    TagFilterSimple("Junior"),
    TagFilterSimple("Backend"),
    TagFilterSimple("Frontend"),
    TagFilterSimple("Principal"),
])

export const misc = HashSet.fromIterable([
    TagFilterSimple("Diversity"),
    TagFilterSimple("Equity"),
    TagFilterSimple("Inclusion"),
    TagFilter({name: "Full-Time", pattern: RegExp(/(^|\b|\s)(full.{0,2}time)($|\b|\s)/, "gmi")}),
    TagFilter({name: "Full-Stack", pattern: RegExp(/(^|\b|\s)(full.{0,2}stack)($|\b|\s)/, "gmi")}),
])